CREATE DATABASE /*!32312 IF NOT EXISTS*/ business_dwh /*!40100 DEFAULT CHARACTER SET latin1 */;

USE business_dwh;


DROP TABLE IF EXISTS dim_pays;
CREATE TABLE dim_pays (
  pays_key int NOT NULL,
  code varchar(3) NOT NULL,
  nom_pays varchar(64) NOT NULL,
  continent varchar(64) NOT NULL,
  region varchar(64) NOT NULL,
  population enum('1-10,000', '10,000-100,000', '100,000-500,000', '500,000-1,000,000', '1,000,000-5,000,000', '5,000,000-10,000,000', '10,000,000-50,000,000', '50,000,000-100,000,000', '100,000,000+') NOT NULL,
  life_expectancy enum('1-50', '50-70', '70+') NOT NULL,

  PRIMARY KEY (pays_key)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS dim_date;
CREATE TABLE dim_date (
  date_key int NOT NULL,
  year int NOT NULL,

  PRIMARY KEY (date_key)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS fact_pib;
CREATE TABLE fact_pib (
  pib_key int NOT NULL,
  pays_key int NOT NULL,
  date_key int NOT NULL,

  pib real NOT NULL,
  croissance_pib real NOT NULL,

  KEY dim_pays_fact_pib_fk (pays_key),
  KEY dim_date_fact_pib_fk (date_key),

  PRIMARY KEY (pib_key)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS fact_immigres;
CREATE TABLE fact_immigres (
  immigres_key int NOT NULL,
  pays_key int NOT NULL,
  date_key int NOT NULL,

  immigres_AFG bigint NOT NULL,
  immigres_AGO bigint NOT NULL,
  immigres_ALB bigint NOT NULL,
  immigres_AND bigint NOT NULL,
  immigres_ARE bigint NOT NULL,
  immigres_ARG bigint NOT NULL,
  immigres_ARM bigint NOT NULL,
  immigres_ATG bigint NOT NULL,
  immigres_AUS bigint NOT NULL,
  immigres_AUT bigint NOT NULL,
  immigres_AZE bigint NOT NULL,
  immigres_BDI bigint NOT NULL,
  immigres_BEL bigint NOT NULL,
  immigres_BEN bigint NOT NULL,
  immigres_BFA bigint NOT NULL,
  immigres_BGD bigint NOT NULL,
  immigres_BGR bigint NOT NULL,
  immigres_BHR bigint NOT NULL,
  immigres_BHS bigint NOT NULL,
  immigres_BIH bigint NOT NULL,
  immigres_BLR bigint NOT NULL,
  immigres_BLZ bigint NOT NULL,
  immigres_BMU bigint NOT NULL,
  immigres_BOL bigint NOT NULL,
  immigres_BRA bigint NOT NULL,
  immigres_BRB bigint NOT NULL,
  immigres_BRN bigint NOT NULL,
  immigres_BTN bigint NOT NULL,
  immigres_BWA bigint NOT NULL,
  immigres_CAF bigint NOT NULL,
  immigres_CAN bigint NOT NULL,
  immigres_CHE bigint NOT NULL,
  immigres_CHL bigint NOT NULL,
  immigres_CHN bigint NOT NULL,
  immigres_CIV bigint NOT NULL,
  immigres_CMR bigint NOT NULL,
  immigres_COD bigint NOT NULL,
  immigres_COG bigint NOT NULL,
  immigres_COK bigint NOT NULL,
  immigres_COL bigint NOT NULL,
  immigres_COM bigint NOT NULL,
  immigres_CPV bigint NOT NULL,
  immigres_CRI bigint NOT NULL,
  immigres_CSK bigint NOT NULL,
  immigres_CUB bigint NOT NULL,
  immigres_CYP bigint NOT NULL,
  immigres_CZE bigint NOT NULL,
  immigres_DEU bigint NOT NULL,
  immigres_DJI bigint NOT NULL,
  immigres_DMA bigint NOT NULL,
  immigres_DNK bigint NOT NULL,
  immigres_DOM bigint NOT NULL,
  immigres_DZA bigint NOT NULL,
  immigres_ECU bigint NOT NULL,
  immigres_EGY bigint NOT NULL,
  immigres_ERI bigint NOT NULL,
  immigres_ESP bigint NOT NULL,
  immigres_EST bigint NOT NULL,
  immigres_ETH bigint NOT NULL,
  immigres_FIN bigint NOT NULL,
  immigres_FJI bigint NOT NULL,
  immigres_FRA bigint NOT NULL,
  immigres_FSM bigint NOT NULL,
  immigres_GAB bigint NOT NULL,
  immigres_GBR bigint NOT NULL,
  immigres_GEO bigint NOT NULL,
  immigres_GHA bigint NOT NULL,
  immigres_GIN bigint NOT NULL,
  immigres_GMB bigint NOT NULL,
  immigres_GNB bigint NOT NULL,
  immigres_GNQ bigint NOT NULL,
  immigres_GRC bigint NOT NULL,
  immigres_GRD bigint NOT NULL,
  immigres_GTM bigint NOT NULL,
  immigres_GUM bigint NOT NULL,
  immigres_GUY bigint NOT NULL,
  immigres_HKG bigint NOT NULL,
  immigres_HND bigint NOT NULL,
  immigres_HRV bigint NOT NULL,
  immigres_HTI bigint NOT NULL,
  immigres_HUN bigint NOT NULL,
  immigres_IDN bigint NOT NULL,
  immigres_IND bigint NOT NULL,
  immigres_IRL bigint NOT NULL,
  immigres_IRN bigint NOT NULL,
  immigres_IRQ bigint NOT NULL,
  immigres_ISL bigint NOT NULL,
  immigres_ISR bigint NOT NULL,
  immigres_ITA bigint NOT NULL,
  immigres_JAM bigint NOT NULL,
  immigres_JOR bigint NOT NULL,
  immigres_JPN bigint NOT NULL,
  immigres_KAZ bigint NOT NULL,
  immigres_KEN bigint NOT NULL,
  immigres_KGZ bigint NOT NULL,
  immigres_KHM bigint NOT NULL,
  immigres_KIR bigint NOT NULL,
  immigres_KNA bigint NOT NULL,
  immigres_KOR bigint NOT NULL,
  immigres_KWT bigint NOT NULL,
  immigres_LAO bigint NOT NULL,
  immigres_LBN bigint NOT NULL,
  immigres_LBR bigint NOT NULL,
  immigres_LBY bigint NOT NULL,
  immigres_LCA bigint NOT NULL,
  immigres_LIE bigint NOT NULL,
  immigres_LKA bigint NOT NULL,
  immigres_LSO bigint NOT NULL,
  immigres_LTU bigint NOT NULL,
  immigres_LUX bigint NOT NULL,
  immigres_LVA bigint NOT NULL,
  immigres_MAC bigint NOT NULL,
  immigres_MAR bigint NOT NULL,
  immigres_MCO bigint NOT NULL,
  immigres_MDA bigint NOT NULL,
  immigres_MDG bigint NOT NULL,
  immigres_MDV bigint NOT NULL,
  immigres_MEX bigint NOT NULL,
  immigres_MHL bigint NOT NULL,
  immigres_MKD bigint NOT NULL,
  immigres_MLI bigint NOT NULL,
  immigres_MLT bigint NOT NULL,
  immigres_MMR bigint NOT NULL,
  immigres_MNE bigint NOT NULL,
  immigres_MNG bigint NOT NULL,
  immigres_MOZ bigint NOT NULL,
  immigres_MRT bigint NOT NULL,
  immigres_MUS bigint NOT NULL,
  immigres_MWI bigint NOT NULL,
  immigres_MYS bigint NOT NULL,
  immigres_NAM bigint NOT NULL,
  immigres_NER bigint NOT NULL,
  immigres_NGA bigint NOT NULL,
  immigres_NIC bigint NOT NULL,
  immigres_NIU bigint NOT NULL,
  immigres_NLD bigint NOT NULL,
  immigres_NOR bigint NOT NULL,
  immigres_NPL bigint NOT NULL,
  immigres_NRU bigint NOT NULL,
  immigres_NZL bigint NOT NULL,
  immigres_OMN bigint NOT NULL,
  immigres_PAK bigint NOT NULL,
  immigres_PAN bigint NOT NULL,
  immigres_PER bigint NOT NULL,
  immigres_PHL bigint NOT NULL,
  immigres_PLW bigint NOT NULL,
  immigres_PNG bigint NOT NULL,
  immigres_POL bigint NOT NULL,
  immigres_PRI bigint NOT NULL,
  immigres_PRK bigint NOT NULL,
  immigres_PRT bigint NOT NULL,
  immigres_PRY bigint NOT NULL,
  immigres_PSE bigint NOT NULL,
  immigres_QAT bigint NOT NULL,
  immigres_ROU bigint NOT NULL,
  immigres_RUS bigint NOT NULL,
  immigres_RWA bigint NOT NULL,
  immigres_SAU bigint NOT NULL,
  immigres_SCG bigint NOT NULL,
  immigres_SDN bigint NOT NULL,
  immigres_SEN bigint NOT NULL,
  immigres_SGP bigint NOT NULL,
  immigres_SLB bigint NOT NULL,
  immigres_SLE bigint NOT NULL,
  immigres_SLV bigint NOT NULL,
  immigres_SMR bigint NOT NULL,
  immigres_SOM bigint NOT NULL,
  immigres_SRB bigint NOT NULL,
  immigres_STP bigint NOT NULL,
  immigres_SUN bigint NOT NULL,
  immigres_SUR bigint NOT NULL,
  immigres_SVK bigint NOT NULL,
  immigres_SVN bigint NOT NULL,
  immigres_SWE bigint NOT NULL,
  immigres_SWZ bigint NOT NULL,
  immigres_SYC bigint NOT NULL,
  immigres_SYR bigint NOT NULL,
  immigres_TCD bigint NOT NULL,
  immigres_TGO bigint NOT NULL,
  immigres_THA bigint NOT NULL,
  immigres_TJK bigint NOT NULL,
  immigres_TKL bigint NOT NULL,
  immigres_TKM bigint NOT NULL,
  immigres_TLS bigint NOT NULL,
  immigres_TON bigint NOT NULL,
  immigres_TOT bigint NOT NULL,
  immigres_TTO bigint NOT NULL,
  immigres_TUN bigint NOT NULL,
  immigres_TUR bigint NOT NULL,
  immigres_TUV bigint NOT NULL,
  immigres_TWN bigint NOT NULL,
  immigres_TZA bigint NOT NULL,
  immigres_UGA bigint NOT NULL,
  immigres_UKR bigint NOT NULL,
  immigres_URY bigint NOT NULL,
  immigres_USA bigint NOT NULL,
  immigres_UUU bigint NOT NULL,
  immigres_UZB bigint NOT NULL,
  immigres_VCT bigint NOT NULL,
  immigres_VEN bigint NOT NULL,
  immigres_VNM bigint NOT NULL,
  immigres_VUT bigint NOT NULL,
  immigres_WSM bigint NOT NULL,
  immigres_YEM bigint NOT NULL,
  immigres_YYY bigint NOT NULL,
  immigres_ZAF bigint NOT NULL,
  immigres_ZMB bigint NOT NULL,
  immigres_ZWE bigint NOT NULL,

  KEY dim_pays_fact_immigres_fk (pays_key),
  KEY dim_date_fact_immigres_fk (date_key),

  PRIMARY KEY (immigres_key)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
